# -*- coding: utf-8 -*-
"""typing test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_owYjDhF31AeEe-zkIs_7cMTiKfXFVZ
"""

import time
String = 'typing speed test'
wordcount = len(String.split())
print(String)
while True:
    t0 = time.time()
    inputtext = str(input('Enter the Sentence:'))
    t1 = time.time()
    accuracy = len(set(inputtext.split()) & set(String.split()))
    accuracy = accuracy/wordcount
    timetaken = t1-t0
    wpm = wordcount/timetaken
    print("WPM", wpm, "Accuracy", accuracy, "Timetaken", timetaken)

